---
title: "exp population"
author: "黃楷越"
date: "2024-10-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
normal exponentioal

```{r cars}
r = c(0.1,0,-0.1)
n0 = 10
t = c(0:20)

N = outer(t,r,function(t,r) (1+r)^t*n0)
matplot(t,N)
legend('topleft',paste('r=',r),pch=paste(1:3),col=1:3)


```



```{r pressure, echo=FALSE}
r = 0.5
K = 500
n0 = 5
tmax = 50
N = rep(n0,tmax+1)

logistic = function(N,K,r) (1+(1-N/K)*r)*N

for (t in 1:tmax){
  N[t+1]= logistic(N[t],K,r)
}
plot(0:tmax,N)

```

```{r}
r = c(0.5,0,-0.5)
n0 = 10
tDisc = 0:50
tCont = seq(0,50,0.1)

Nd = outer(tDisc,r,function(t,r) (1+r)^t*n0)
Nc = outer(tCont,r,function(t,r) exp(r*t)*n0)
matplot(tDisc,Nd )
matplot(tCont,Nc )
legend('topleft',paste('r=',r),pch=paste(1:3),col=1:3)




```


```{r pressure, echo=FALSE}
library(deSolve)

# 參數設定
r <- 1
K <- 500
N0 <- 5
tmax <- 50

# logistic growth微分方程的形式
logistic_continuous <- function(t, N, params) {
  with(as.list(params), {
    dN <- r * N * (1 - N / K)
    return(list(dN))
  })
}

# 初始條件與時間
params <- c(r = r, K = K)
times <- seq(0, tmax, by = 0.1)
state <- c(N = N0)

# 使用ode函數求解
out <- ode(y = state, times = times, func = logistic_continuous, parms = params)

# 繪圖
plot(out, main = "Continuous-time Logistic Growth Model", ylab = "Population Size (N)", xlab = "Time (t)")
```